# Generated by Django 4.1.5 on 2023-01-12 00:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('send_confirm', '0002_alter_article_us'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='us',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
