# Generated by Django 4.1.5 on 2023-01-12 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_confirm', '0004_alter_article_us_alter_rating_article_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infos_user',
            name='name',
        ),
        migrations.AddField(
            model_name='infos_user',
            name='username',
            field=models.CharField(default='test', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='infos_user',
            name='address',
            field=models.CharField(max_length=350),
        ),
        migrations.AlterField(
            model_name='infos_user',
            name='phone_number',
            field=models.TextField(max_length=20),
        ),
    ]
