# Generated by Django 4.1.5 on 2023-01-12 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('send_confirm', '0005_remove_infos_user_name_infos_user_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='us',
        ),
        migrations.AddField(
            model_name='article',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='send_confirm.infos_user'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='send_confirm.infos_user'),
        ),
    ]
