# Generated by Django 4.1.5 on 2023-01-12 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('send_confirm', '0006_remove_article_us_article_user_alter_rating_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infos_user',
            old_name='user_infos',
            new_name='user_auth',
        ),
    ]
