# Generated by Django 4.1.5 on 2023-01-13 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_confirm', '0007_rename_user_infos_infos_user_user_auth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infos_user',
            name='address',
            field=models.CharField(blank=True, max_length=350),
        ),
    ]
