# Generated by Django 4.1.5 on 2023-01-14 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('send_confirm', '0009_rename_username_infos_user_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='user',
            new_name='auth_user',
        ),
    ]
