# Generated by Django 4.1.5 on 2023-01-14 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_confirm', '0010_rename_user_article_auth_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infos_user',
            name='author',
            field=models.CharField(max_length=50),
        ),
    ]
