# Generated by Django 4.1.5 on 2023-01-14 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('send_confirm', '0011_alter_infos_user_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='auth_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='send_confirm.infos_user'),
        ),
    ]
