# Generated by Django 4.1.5 on 2023-01-14 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('send_confirm', '0012_alter_article_auth_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='auth_user',
            new_name='user',
        ),
    ]
