# Generated by Django 4.1.5 on 2023-01-15 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('send_confirm', '0014_alter_article_user_alter_rating_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infos_user',
            name='author',
        ),
    ]
