# Generated by Django 4.1.5 on 2023-01-15 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('send_confirm', '0015_remove_infos_user_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infos_user',
            name='phone',
        ),
    ]
