# Generated by Django 4.1.5 on 2023-01-15 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_confirm', '0016_remove_infos_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='infos_user',
            name='phone',
            field=models.TextField(blank=True, max_length=20),
        ),
    ]
