# Generated by Django 4.1.7 on 2023-02-26 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('send_confirm', '0020_remove_post_pub_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.RemoveField(
            model_name='post1',
            name='pub_date',
        ),
    ]
